name: Build zip

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run build
              env:
                  GIT_CLONE_TOKEN: ${{ secrets.GIT_CLONE_TOKEN }}
            - run: npm run wrap
            - id: upload
              uses: ethersphere/swarm-actions/upload-dir@v0
              with:
                  bee-url: https://api.gateway.ethswarm.org
                  postage-batch-id: '0000000000000000000000000000000000000000000000000000000000000000'
                  dir: 'out'
                  index-document: 'static.zip'
            - shell: bash
              run: 'echo "Swarm Hash: ${{ steps.upload.outputs.reference }}"'
            - id: version
              run: npm run version
            - name: release
              uses: actions/create-release@v1
              id: release
              with:
                  draft: false
                  prerelease: false
                  release_name: ${{ steps.version.outputs.version }}
                  tag_name: ${{ steps.version.outputs.version }}
              env:
                  GITHUB_TOKEN: ${{ github.token }}
            - name: upload static zip
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ steps.release.outputs.upload_url }}
                  asset_path: out/static.zip
                  asset_name: static.zip
                  asset_content_type: application/zip
              env:
                  GITHUB_TOKEN: ${{ github.token }}
