name: Build zip

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: GIT_CLONE_TOKEN=${{ secrets.GIT_CLONE_TOKEN }} npm run build
            - run: npm run wrap
            - uses: ethersphere/swarm-actions/upload-dir@v0
              with:
                  bee-url: https://api.gateway.ethswarm.org
                  postage-batch-id: '0000000000000000000000000000000000000000000000000000000000000000'
                  dir: 'static'
                  index-document: 'static.zip'
